// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc93.FinalRobot.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.WaitCommand;
import org.usfirst.frc93.FinalRobot.Robot;
import org.usfirst.frc93.FinalRobot.RobotMap;

/**
 *
 */
public class ClimberGroup extends CommandGroup {

    public ClimberGroup() {
       addSequential(new RaiseSliderCommand(1060));
       addSequential(new TiltCommand());
       addSequential(new PullDownSliderCommand(-300));
       addSequential(new RetractTiltCommand());       
       //addSequential(new GripperLockCommand());      
       //addSequential(new RaiseSliderCommand(1060));
       //addSequential(new PullDownSliderCommand(-300));
       ///addSequential(new RaiseSliderCommand(744));
      // addSequential(new PullDownSliderCommand(330));
      // addSequential(new GripperReleaseCommand());
      // addSequential(new MechanicalLockCommand());       
      // addSequential(new PullDownSliderCommand(-390));
      // addSequential(new RaiseSliderCommand(1060));
       //addSequential(new MechanicalReleaseCommand());
       //addSequential(new PullDownSliderCommand(-300));
       //addSequential(new RaiseSliderCommand(1060));
    }

    public void execute() {
        //if (Robot.oi.doneAligning.get()) {
        //    Robot.climber.setAligned();
        //}
        if(true/*Robot.climber.isAligned()*/){
            super.execute();
        }
    }
    public void end(){
        super.end();
        //RobotMap.climberController.disable();
        Robot.climber.resetAligned();
    }
}
