// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc93.Team93Robot2015.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc93.Team93Robot2015.Robot;
import org.usfirst.frc93.Team93Robot2015.RobotMap;
import org.usfirst.frc93.Team93Robot2015.subsystems.Drive;

/**
 *
 */
public class DriveForward extends Command {

    boolean finished = false;
    double m_driveDistance;

    // private boolean m_finished = false;

    public DriveForward(double driveDistance, double maxError) {
        // Use requires() here to declare subsystem dependencies
        m_driveDistance = driveDistance;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        RobotMap.leftMotorEncoder.reset();
        RobotMap.rightMotorEncoder.reset();
        Drive.driveControl.reset();
        Drive.driveControl.enable();
        Drive.driveControl.setSetpoint(m_driveDistance);
        Drive.driveGroup.setGains(1.0);
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {

    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {

        // double currentError = RobotMap.driveControl.getError();

        // we ignored a note in the onTarget documentation that depends on the
        // input range having been set

        return (true);
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Drive.setAllMotors(0.0);
        Drive.driveControl.disable();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        this.end();
    }
}
