// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc93.Team93Robot2015.subsystems;

import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Switches extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    // double leftMotorOne = RobotMap.leftMotorOne.get();
    // double leftMotorTwo = RobotMap.leftMotorTwo.get();
    // double rightMotorOne = RobotMap.rightMotorOne.get();
    // double rightMotorTwo = RobotMap.rightMotorTwo.get();
    // boolean limitSwitchOne = RobotMap.limitSwitchOne.get();
    // boolean limitSwitchTwo = RobotMap.limitSwitchTwo.get();

    @Override
    public void initDefaultCommand() {
        // if (limitSwitchOne = true) {
        // leftMotorOne = 0;
        // leftMotorTwo = 0;
        // }
        // if (limitSwitchTwo = true) {
        // rightMotorOne = 0;
        // rightMotorTwo = 0;
        // }
        // RobotMap.leftMotorOne.set(leftMotorOne);
        // RobotMap.leftMotorTwo.set(leftMotorTwo);
        // RobotMap.rightMotorOne.set(rightMotorOne);
        // RobotMap.rightMotorTwo.set(rightMotorTwo);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());

    }
}
