// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc93.Team93Robot2015.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc93.Team93Robot2015.Robot;

/**
 * This command moves the drawbridge
 */
public class MoveDrawbridge extends Command {

    public MoveDrawbridge() {
        // Use requires() here to declare subsystem dependencies
        requires(Robot.drawbridge);
    }

    // Called just before this Command runs the first time
    @Override
    /**
     * This function sets the drawbridge opposite of its current state.
     * If the drawbridge is in, extend it.
     * If the drawbridge is out, retract it.
     */
    protected void initialize() {
        if (Robot.drawbridge.getDrawbridgeState()) {
            Robot.drawbridge.extendDrawbridge();
        }
        else {
            Robot.drawbridge.retractDrawbridge();
        }
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return true;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
