// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc93.Team93Robot2015;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Talon;

import java.util.Scanner;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // Placeholder variables
    static int a;
    static int b;
    static int c;
    static int d;
    static int e;

    // Autonomous Selector Switches
    public static DigitalInput autonomousSelectorOne = new DigitalInput(a); // INPUT
                                                                            // VALUES
                                                                            // WILL
                                                                            // NEED
                                                                            // TO
                                                                            // BE
                                                                            // ADJUSTED
    public static DigitalInput autonomousSelectorTwo = new DigitalInput(b);
    public static DigitalInput autonomousSelectorThree = new DigitalInput(c);
    public static DigitalInput autonomousSelectorFour = new DigitalInput(d);
    public static DigitalInput autonomousSelectorFive = new DigitalInput(e);
    // Limit Switches
    public static DigitalInput limitSwitchOne = new DigitalInput(0);
    public static DigitalInput limitSwitchTwo = new DigitalInput(1);
    public static DigitalInput rakeLimitSwitch = new DigitalInput(2);
    // Encoders
    public static Encoder leftMotorEncoder = new Encoder(6, 7);
    public static Encoder rightMotorEncoder = new Encoder(4, 5);
    public static Encoder rakeMotorEncoder = new Encoder(8, 9);
    // Motors
    public static Talon leftMotorOne = new Talon(0);
    public static Talon leftMotorTwo = new Talon(1);
    public static Talon rightMotorOne = new Talon(2);
    public static Talon rightMotorTwo = new Talon(3);
    public static Talon rakeMotor = new Talon(4);
    // Pneumatic Servos
    public static DoubleSolenoid drawbridgePneumaticArm = new DoubleSolenoid(0,
            1);
    public static DoubleSolenoid drawbridgePneumaticArmLock = new DoubleSolenoid(
            2, 3);

    // public static DoubleSolenoid drawbridgePneumaticArmTwo = new
    // DoubleSolenoid(
    // 2, 3);
    //
    public static Scanner userInput = new Scanner(System.in);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
